### ISSUE TITLE
Unable to Login with Facebook

### ISSUE THREAD

**Issue by uint16** [b-nugent/344WebApp#1]
Run the project locally, try to login with facebook account

Source: AccountController.cs Line 334

Error Message:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 50 - Local Database Runtime error occurred. The specified LocalDB instance does not exist.
![capture](https://cloud.githubusercontent.com/assets/3052799/10269068/f16a5cee-6a98-11e5-91a7-85b06055e7ae.PNG)

**Comment by andrewpop1118** [comment]
This is because the LocalDB instance has not been created on your machine. We have discussed this issue and it is now solved.
