### ISSUE TITLE
NullReferenceException when going to the index (main) page without logging in

### ISSUE THREAD

**Issue by andrewpop1118** [b-nugent/344WebApp#3]
HomeController.cs - Line 17: Object reference not set to an instance of an object.

**Comment by uint16** [comment]
![capture2](https://cloud.githubusercontent.com/assets/3052799/10270412/90c0c286-6abe-11e5-8397-8db91a45588a.PNG)

**Comment by andrewpop1118** [comment]
This is no longer an issue as of commit a46032f.
